"""
unsupervised_01_data_split.py
-----------------------------
Prepares the datasets for the unsupervised fault detection pipeline.
Reads the feature CSVs generated by 02_feature_extraction.py and splits them
such that the training set only contains healthy samples. The validation
and testing sets will contain a mix of healthy and faulty samples.
"""

import os
import pandas as pd
from sklearn.model_selection import train_test_split

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROCESSED_DIR = os.path.join(BASE_DIR, "data", "processed")
OUT_DIR = os.path.join(BASE_DIR, "data", "unsupervised")
WINDOWS = [300, 400, 500, 600, 700, 800, 900, 1000]

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    print("======================================================")
    print(" Unsupervised Data Split for Gearbox Fault Detection")
    print("======================================================")
    
    for W in WINDOWS:
        filepath = os.path.join(PROCESSED_DIR, f"features_W{W}.csv")
        if not os.path.exists(filepath):
            print(f"[SKIP] File not found: {filepath}. Run 02_feature_extraction.py first.")
            continue
            
        print(f"\nProcessing window size W = {W} ...")
        df = pd.read_csv(filepath)
        
        # Separate the healthy and faulty rows
        df_healthy = df[df["label"] == 0]
        df_faulty = df[df["label"] == 1]
        
        # Split healthy into Train (70%), Val (15%), Test (15%)
        # Stratify on the load condition so we have equal rep. of 0-90% loads
        train_h, temp_h = train_test_split(df_healthy, test_size=0.30, random_state=42, stratify=df_healthy["load"])
        val_h, test_h = train_test_split(temp_h, test_size=0.50, random_state=42, stratify=temp_h["load"])
        
        # Split faulty into Val (50%), Test (50%)
        # We don't train on faulty data at all in an unsupervised setting
        val_f, test_f = train_test_split(df_faulty, test_size=0.50, random_state=42, stratify=df_faulty["load"])
        
        # Combine the healthy and faulty parts for val/test, then shuffle
        train_df = train_h.copy()
        val_df = pd.concat([val_h, val_f]).sample(frac=1, random_state=42).reset_index(drop=True)
        test_df = pd.concat([test_h, test_f]).sample(frac=1, random_state=42).reset_index(drop=True)
        
        train_path = os.path.join(OUT_DIR, f"train_W{W}.csv")
        val_path = os.path.join(OUT_DIR, f"val_W{W}.csv")
        test_path = os.path.join(OUT_DIR, f"test_W{W}.csv")
        
        train_df.to_csv(train_path, index=False)
        val_df.to_csv(val_path, index=False)
        test_df.to_csv(test_path, index=False)
        
        print(f"  Saved splits for W={W}:")
        print(f"    Train: {len(train_df)} samples (100% healthy)")
        print(f"    Val:   {len(val_df)} samples (mix of healthy & faulty)")
        print(f"    Test:  {len(test_df)} samples (mix of healthy & faulty)")
        
    print("\n[OK] Data splitting for unsupervised learning is complete.")

if __name__ == "__main__":
    main()
